---
- name: install apache
  yum:
    name: "{{httpd_pkg}}"
    state: present
- name: enable apache at boot
  service:
    name: "{{httpd_service}}"
    enabled: yes
- name: start apache
  service:
    name: "{{ httpd_service }}"
    state: started
